sonar.projectKey=reservation-service
sonar.projectName=Reservation Service
sonar.sources=app
sonar.host.url=http://localhost:9000
sonar.login=${env.SONAR_TOKEN}
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10
