services:
  salle-db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: salle_db
    ports:
      - "5433:5432"
    volumes:
      - salle_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d salle_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices_default

  salle-service:
    build: .
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: "postgresql://admin:admin123@salle-db/salle_db"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      salle-db:
        condition: service_healthy
    networks:
      - microservices_default
    command: >
      bash -c "while ! nc -z salle-db 5432; do sleep 2; done
      && gunicorn --bind 0.0.0.0:5000 wsgi:app"

networks:
  microservices_default:
    driver: bridge
    

volumes:
  salle_data:
